version: '3.1'

services:
  database:
    image: 'postgres:14.4-alpine'
    ports:
      - '5432:5432'
    volumes:
      - globerfloor:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  globerfloor:
